### ISSUE TITLE
Remove GBIF Registration sidebar menu item from Configuration

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#975] opened 2021-07-13 17:14 UTC
![image](https://user-images.githubusercontent.com/12532430/125496528-82cc8d78-4a56-43e9-b498-9095e786ac58.png)
It doesn't do anything currently and is not in this release

**Comment by maxxxxxdlp** [comment] 2021-07-13 17:58
Duplicate of https://github.com/specify/specify6/issues/973

**Comment by tlammer** [comment] 2021-07-15 22:02
different from #973

**Closed** 2022-09-20 16:20 UTC
Labels: bug, fixed, Confirmed Fixed, Blocker
