### ISSUE TITLE
Spurious localization warning on startup.

### ISSUE THREAD

**Issue by timo11** [specify/specify6#620] opened 2020-02-25 17:29 UTC
The msg below can appear (almost always appears on Macs) for newly created databases, even when the discipline schema HAS been localized to English.

**Comment by timo11** [comment] 2020-02-25 17:32
![Screen Shot 2020-02-25 at 11 26 38 AM](https://user-images.githubusercontent.com/2915306/75271854-7ff11780-57c2-11ea-971e-33801c12244f.png)

**Comment by timo11** [comment] 2020-02-25 17:41
Should be fixed for newly created dbs. Pre-existing 6.8.00 dbs with the issue can probably fixed by running "update splocaleitemstr set country = null where language = 'en';"

**Comment by maxxxxxdlp** [comment] 2020-02-25 17:59
Duplicate of #476 
I will test this fix and mark it as "Confirmed Fixed" in both places

**Comment by maxxxxxdlp** [comment] 2020-02-27 16:59
> Tested 3 times on different computers. Seems fixed. Though, this bug is hard to test because it appears randomly on different systems. Will update this issue if it will occur again

#476

**Comment by norinespears** [comment] 2020-02-27 19:36
Worked for me too!!

**Closed** 2020-04-20 15:26 UTC
Labels: Confirmed Fixed, bug, duplicate, fixed
