### ISSUE TITLE
If you return an uncataloged item in loan, the Loan Return Preparations column says -#

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#78] opened 2018-03-06 16:13 UTC
It does get marked as resolved, but the count is -#
![image](https://user-images.githubusercontent.com/12532430/37049742-7851a706-2137-11e8-911c-a92fe3ccd08e.png)

**Comment by timo11** [comment] 2018-03-06 16:37
This almost certainly a duplicate of #46. But maybe not.

**Comment by tlammer** [comment] 2018-03-06 16:38
I thought so, that's why I cleared it out and moved the data to 46.

**Comment by timo11** [comment] 2018-03-07 20:22
people who use uncataloged items who don't like the " - #" format will have to change the loanreturnpreparation table format and/or aggregator.

**Closed** 2018-09-14 21:31 UTC
Labels: QA:N/A, invalid
