### ISSUE TITLE
Duplicate data from uploaded data sets are not highlighted as invalid in WB

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify6#143] opened 2018-05-31 19:17 UTC
Duplicate catalog numbers which have been uploaded do not get highlighted as invalid in the workbench. However, trying to upload these records gives a message saying the records have already been uploaded.

**Comment by timo11** [comment] 2018-05-31 19:26
duplicate of #142

**Closed by timo11** 2018-05-31 19:26 UTC
Labels: bug
