### ISSUE TITLE
Error when logging into database using mariadb

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify6#510] opened 2020-01-03 21:07 UTC
I'm getting the following error message when I log into databases using mariadb
![Screenshot (1)](https://user-images.githubusercontent.com/28809154/71749351-c79a9900-2e3a-11ea-8fca-8dc5e33dee52.png)

**Comment by maxxxxxdlp** [comment] 2020-01-03 23:00
Duplicate of #476

**Closed** 2020-01-03 23:00 UTC
Labels: bug, duplicate
