### ISSUE TITLE
Allow pre-selection of loan preparations for return.

### ISSUE THREAD

**Issue by timo11** [specify/specify6#863] opened 2021-04-13 15:33 UTC
Currently, when the "return" button on the loan form is clicked, all items are displayed in the return dialog. Users need to be able to select items by scanning barcodes, entering IDs, or selecting Recordsets.

**Comment by tlammer** [comment] 2021-04-27 15:52
duplicate of #311

**Closed** 2022-09-20 16:22 UTC
Labels: duplicate, enhancement, fixed, Confirmed Fixed
