### ISSUE TITLE
Error when updating database to 6.8.01

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify6#929] opened 2021-05-26 17:59 UTC
I get these errors when I update a database to the latest version of 6.8.01:

![Screenshot (197)](https://user-images.githubusercontent.com/28809154/119708897-3ad2ef80-be22-11eb-9b09-ed2bc8ba6ccd.png)
![Screenshot (196)](https://user-images.githubusercontent.com/28809154/119708900-3b6b8600-be22-11eb-893b-527b1a43e3ea.png)

**Comment by asommerville20** [comment] 2021-05-27 14:53
I found this error in another place--when I try and open an uncataloged loan form under interactions, clicking uncataloged gives me the above error; then, I get a message that specify needs to shut down (specify doesn't completely shutdown but the form can't be opened). This could also be a seperate bug I'm not sure

**Comment by timo11** [comment] 2021-06-08 15:02
duplicate of #937

**Closed by timo11** 2021-06-08 15:02 UTC
Labels: bug
