### ISSUE TITLE
Exception when updating database to 6.8

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify6#687] opened 2020-03-23 16:31 UTC
How to replicate: 

- Start with a current version of Specify 6.7.04 and a database that has not been updated
- Update to the newest version of Specify 6.8 on the web
- Try to log in to the new version of Specify and it will ask if you want to update
- Say 'Continue'
- You receive a dialog suggesting that you backup 
- Press 'Exit' in stead of Continue

The following error appears after the 'application will now exit' window is closed:
class_name: edu.ku.brc.specify.config.AppPrefsGlobalDBIOIImpl
comments: 

stack_trace: 
org.hibernate.exception.SQLGrammarException: could not load an entity: [edu.ku.brc.specify.datamodel.Agent#3]
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:67)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.loader.Loader.loadEntity(Loader.java:1874)
	at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:48)
	at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:42)
	at org.hibernate.persister.entity.AbstractEntityPersister.load(AbstractEntityPersister.java:3044)
	at org.hibernate.event.def.DefaultLoadEventListener.loadFromDatasource(DefaultLoadEventListener.java:395)
	at org.hibernate.event.def.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:375)
	at org.hibernate.event.def.DefaultLoadEventListener.load(DefaultLoadEventListener.java:139)
	at org.hibernate.event.def.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:179)
	at org.hibernate.event.def.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:103)
	at org.hibernate.impl.SessionImpl.fireLoad(SessionImpl.java:878)
	at org.hibernate.impl.SessionImpl.internalLoad(SessionImpl.java:846)
	at org.hibernate.type.EntityType.resolveIdentifier(EntityType.java:557)
	at org.hibernate.type.EntityType.resolve(EntityType.java:379)
	at org.hibernate.engine.TwoPhaseLoad.initializeEntity(TwoPhaseLoad.java:116)
	at org.hibernate.loader.Loader.initializeEntitiesAndCollections(Loader.java:854)
	at org.hibernate.loader.Loader.doQuery(Loader.java:729)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:236)
	at org.hibernate.loader.Loader.doList(Loader.java:2220)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2104)
	at org.hibernate.loader.Loader.list(Loader.java:2099)
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:378)
	at org.hibernate.hql.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:338)
	at org.hibernate.engine.query.HQLQueryPlan.performList(HQLQueryPlan.java:172)
	at org.hibernate.impl.SessionImpl.list(SessionImpl.java:1121)
	at org.hibernate.impl.QueryImpl.list(QueryImpl.java:79)
	at edu.ku.brc.specify.dbsupport.HibernateDataProviderSession.getDataList(HibernateDataProviderSession.java:241)
	at edu.ku.brc.specify.config.SpecifyAppContextMgr.getAppResDir(SpecifyAppContextMgr.java:792)
	at edu.ku.brc.specify.config.AppPrefsGlobalDBIOIImpl.createResDir(AppPrefsGlobalDBIOIImpl.java:51)
	at edu.ku.brc.specify.config.AppPrefsDBIOIImpl.load(AppPrefsDBIOIImpl.java:165)
	at edu.ku.brc.specify.config.AppPrefsDBIOIImpl.exists(AppPrefsDBIOIImpl.java:106)
	at edu.ku.brc.af.prefs.AppPreferences.load(AppPreferences.java:751)
	at edu.ku.brc.af.prefs.AppPreferences.get(AppPreferences.java:398)
	at edu.ku.brc.af.prefs.AppPreferences.get(AppPreferences.java:384)
	at edu.ku.brc.af.prefs.AppPreferences.getBoolean(AppPreferences.java:494)
	at edu.ku.brc.af.prefs.AppPreferences.getBoolean(AppPreferences.java:511)
	at edu.ku.brc.af.core.db.MySQLBackupService.checkForBackUp(MySQLBackupService.java:1254)
	at edu.ku.brc.specify.Specify.doExit(Specify.java:2254)
	at edu.ku.brc.specify.Specify.doCommand(Specify.java:3093)
	at edu.ku.brc.ui.CommandDispatcher.dispatch(CommandDispatcher.java:122)
	at edu.ku.brc.af.ui.db.DatabaseLoginPanel$17.doLoginContinuing2(DatabaseLoginPanel.java:1401)
	at edu.ku.brc.af.ui.db.DatabaseLoginPanel$17$2.exited(DatabaseLoginPanel.java:1347)
	at com.install4j.runtime.installer.helper.apiimpl.ApplicationLauncherImpl$CommFileWaiter.exited(ApplicationLauncherImpl.java:217)
	at com.install4j.runtime.installer.helper.apiimpl.ApplicationLauncherImpl$CommFileWaiter.run(ApplicationLauncherImpl.java:197)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'agent0_.Date1' in 'field list'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
	at com.mysql.jdbc.Util.getInstance(Util.java:372)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:980)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2535)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1911)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2034)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
	at org.hibernate.jdbc.AbstractBatcher.getResultSet(AbstractBatcher.java:186)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:1787)
	at org.hibernate.loader.Loader.doQuery(Loader.java:674)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:236)
	at org.hibernate.loader.Loader.loadEntity(Loader.java:1860)
	... 42 more

task_name: 
title: 
id: f976b698-1604-8199-ff51-b3987e22e306--170f8d4caa0
os_name: Windows 10
os_version: 10.0
java_version: 1.8.0_202
java_vendor: Amazon.com Inc.
max_memory: 954728448
used_memory: 76786448
user_name: y207e325
ip: 192.168.56.1
app_version: 6.8.00

**Comment by timo11** [comment] 2020-03-23 17:06
Unable to duplicate. What databases produce this error?

**Comment by yvonneekanim** [comment] 2020-03-23 17:22
Delaware and Santa Barbara

**Comment by timo11** [comment] 2020-03-23 18:06
which delaware and santa barbara. The latest delaware on specify6 worked for me.

**Comment by timo11** [comment] 2020-03-23 18:20
Never mind the error is happening silently for the delaware db.

**Comment by timo11** [comment] 2020-03-23 18:57
The exception popup should be fixed. Also occasional backup prompts in this situation before specify completely shuts down should no longer occur. There will still be an error in the exception log, when a schema update includes changes to the agent table, but the exit process should run smoothly at the UI level.

**Comment by maxxxxxdlp** [comment] 2020-03-24 14:55
Seems like a duplicate of #509

**Comment by beach53** [comment] 2020-03-24 15:23
So were these two cases of the same bug?

**Comment by maxxxxxdlp** [comment] 2020-03-24 15:28
@beach53 yes. I also had a similar error message when logging in (without schema update) - https://github.com/specify/specify6/issues/685#issuecomment-601897454. I suppose it was caused by a corrupt database, so it is now worth bothering about

**Comment by maxxxxxdlp** [comment] 2020-03-24 17:43
No exception occurs any longer
Tho there is a new problem with it - https://github.com/specify/specify6/issues/509#issuecomment-603400330

**Comment by yvonneekanim** [comment] 2020-03-25 15:50
I'm still getting an exception following the steps I stated in the initial bug

class_name: edu.ku.brc.specify.config.SpecifyAppContextMgr
comments: 

stack_trace: 
org.hibernate.exception.SQLGrammarException: could not load an entity: [edu.ku.brc.specify.datamodel.Agent#3]
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:67)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.loader.Loader.loadEntity(Loader.java:1874)
	at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:48)
	at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:42)
	at org.hibernate.persister.entity.AbstractEntityPersister.load(AbstractEntityPersister.java:3044)
	at org.hibernate.event.def.DefaultLoadEventListener.loadFromDatasource(DefaultLoadEventListener.java:395)
	at org.hibernate.event.def.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:375)
	at org.hibernate.event.def.DefaultLoadEventListener.load(DefaultLoadEventListener.java:139)
	at org.hibernate.event.def.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:179)
	at org.hibernate.event.def.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:103)
	at org.hibernate.impl.SessionImpl.fireLoad(SessionImpl.java:878)
	at org.hibernate.impl.SessionImpl.internalLoad(SessionImpl.java:846)
	at org.hibernate.type.EntityType.resolveIdentifier(EntityType.java:557)
	at org.hibernate.type.EntityType.resolve(EntityType.java:379)
	at org.hibernate.engine.TwoPhaseLoad.initializeEntity(TwoPhaseLoad.java:116)
	at org.hibernate.loader.Loader.initializeEntitiesAndCollections(Loader.java:854)
	at org.hibernate.loader.Loader.doQuery(Loader.java:729)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:236)
	at org.hibernate.loader.Loader.doList(Loader.java:2220)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2104)
	at org.hibernate.loader.Loader.list(Loader.java:2099)
	at org.hibernate.loader.criteria.CriteriaLoader.list(CriteriaLoader.java:94)
	at org.hibernate.impl.SessionImpl.list(SessionImpl.java:1569)
	at org.hibernate.impl.CriteriaImpl.list(CriteriaImpl.java:283)
	at edu.ku.brc.specify.dbsupport.HibernateDataProviderSession.getDataList(HibernateDataProviderSession.java:293)
	at edu.ku.brc.specify.dbsupport.HibernateDataProviderSession.getDataList(HibernateDataProviderSession.java:328)
	at edu.ku.brc.specify.config.SpecifyAppContextMgr.setContext(SpecifyAppContextMgr.java:1297)
	at edu.ku.brc.specify.config.SpecifyAppContextMgr.setContext(SpecifyAppContextMgr.java:1222)
	at edu.ku.brc.specify.Specify.restartApp(Specify.java:2496)
	at edu.ku.brc.specify.Specify.loggedIn(Specify.java:2945)
	at edu.ku.brc.ui.UIHelper$1DBListener.loggedIn(UIHelper.java:1859)
	at edu.ku.brc.af.ui.db.DatabaseLoginPanel.loginOK(DatabaseLoginPanel.java:1066)
	at edu.ku.brc.af.ui.db.DatabaseLoginPanel$17.finished(DatabaseLoginPanel.java:1455)
	at edu.ku.brc.helpers.SwingWorker$1.run(SwingWorker.java:127)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'agent0_.Date1' in 'field list'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
	at com.mysql.jdbc.Util.getInstance(Util.java:372)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:980)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2535)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1911)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2034)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
	at org.hibernate.jdbc.AbstractBatcher.getResultSet(AbstractBatcher.java:186)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:1787)
	at org.hibernate.loader.Loader.doQuery(Loader.java:674)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:236)
	at org.hibernate.loader.Loader.loadEntity(Loader.java:1860)
	... 46 more

task_name: 
title: 
id: f976b698-1604-8199-ff51-b3987e22e306--17111dad3f0
os_name: Windows 10
os_version: 10.0
java_version: 1.8.0_202
java_vendor: Amazon.com Inc.
max_memory: 954728448
used_memory: 424392608
user_name: y207e325
ip: 192.168.56.1
app_version: 6.8.00
collection: No Collection
discipline: No Discipline
division: No Division
institution: No Institution
Collection_number: No Collection Number
Discipline_number: No Discipline Number
Division_number: No Division Number
Institution_number: No Institution Number

**Comment by maxxxxxdlp** [comment] 2020-03-26 16:39
@yvonneekanim can you test this? It works for me with KU Fish

**Closed** 2020-04-20 15:26 UTC
Labels: Confirmed Fixed, bug, fixed
