### ISSUE TITLE
Removing a field from Preparation Properties table in a query causes error

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify6#287] opened 2019-04-15 19:20 UTC
I tried to delete a field from preparation properties that I added to a new query and I got an error message. If I try to delete a prep property field from a previously saved query I don't get any errors. This happens in both CO and Preparation queries.

Here is the error message:

java.lang.RuntimeException: edu.ku.brc.specify.tasks.subpane.qb.QueryBldrPane: unable to determine relationship.recordedBy <-> preparationProperties
	at edu.ku.brc.specify.tasks.subpane.qb.QueryBldrPane.buildFieldQRI(QueryBldrPane.java:4239)
	at edu.ku.brc.specify.tasks.subpane.qb.QueryBldrPane$24.run(QueryBldrPane.java:4340)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by timo11** [comment] 2019-04-15 19:48
The problem is that RecordedBy and MeasurementBy were removed in the final version of the PreparationProperty and CollectionObjectProperty tables.

**Comment by timo11** [comment] 2019-06-11 16:16
The fix for this problem for some reason was never merged from the develop to the master branch.

**Closed** 2019-11-18 18:32 UTC
Labels: Confirmed Fixed, bug, fixed
