### ISSUE TITLE
Preferences > Error message when opening "Auditing" and "Web Portal" tab

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#425] opened 2019-11-29 15:19 UTC
There is no icon for "Auditing" and "Web Portal" tab and whenever I click on them, I get the same error message twice. After clicking "Ok" to close the Message Boxes, the coresponding settings tab opens just fine

Bug is present in both Linux and macOS versions of Specify 6.8.00

<img width="621" alt="Screen Shot 2019-11-29 at 9 14 30 AM" src="https://user-images.githubusercontent.com/40512816/69877823-d82e8100-1288-11ea-9a9f-9753d74da010.png">
<img width="585" alt="Screen Shot 2019-11-29 at 9 14 39 AM" src="https://user-images.githubusercontent.com/40512816/69877825-d82e8100-1288-11ea-92fe-4c5a9dec2fe8.png">
<img width="585" alt="Screen Shot 2019-11-29 at 9 14 42 AM" src="https://user-images.githubusercontent.com/40512816/69877826-d82e8100-1288-11ea-938a-565865aa1158.png">
<img width="606" alt="Screen Shot 2019-11-29 at 9 14 45 AM" src="https://user-images.githubusercontent.com/40512816/69877828-d82e8100-1288-11ea-9497-578ae35127a1.png">
<img width="606" alt="Screen Shot 2019-11-29 at 9 14 47 AM" src="https://user-images.githubusercontent.com/40512816/69877829-d82e8100-1288-11ea-926c-a8927510d26d.png">

**Comment by maxxxxxdlp** [comment] 2019-11-29 15:25
Those tabs are not present in Specify 6.7.04

**Comment by maxxxxxdlp** [comment] 2019-12-02 19:55
Duplicate of #349

**Comment by beach53** [comment] 2019-12-03 22:36
Should not be opening the help, and help is missing

**Comment by timo11** [comment] 2019-12-17 17:43
Duplicate of #348

**Closed** 2019-12-17 17:44 UTC
Labels: duplicate
